name: Docker

on:
  schedule:
    - cron: "31 22 * * 0"
  push:
    branches: [main, dev]
    tags: ["v*.*.*"]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata (default)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ github.repository_owner }}/wyze-bridge
            ghcr.io/${{ github.repository }}
          tags: |
            type=schedule
            type=semver,pattern={{version}}
            type=edge,branch=main,enable=${{ github.event_name == 'push' }}
            type=ref,event=branch,enable=${{ contains(github.ref, 'dev') }}
            type=ref,event=tag

      - name: Docker metadata (hwaccel)
        id: hwmeta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ github.repository_owner }}/wyze-bridge
            ghcr.io/${{ github.repository }}
          flavor: |
            latest=auto
            suffix=-hw,onlatest=true
          tags: |
            type=schedule,suffix=-hw
            type=semver,pattern={{version}},suffix=-hw
            type=edge,branch=main,enable=${{ github.event_name == 'push' }},suffix=-hw
            type=ref,event=branch,enable=${{ contains(github.ref, 'dev') }},suffix=-hw
            type=ref,event=tag,suffix=-hw

      - name: Build and push (default)
        uses: docker/build-push-action@v6
        with:
          context: ./app
          file: ./app/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push (hwaccel)
        uses: docker/build-push-action@v6
        with:
          context: ./app
          file: ./app/Dockerfile.hwaccel
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.hwmeta.outputs.tags }}
          labels: ${{ steps.hwmeta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
